In [1]:
vu = 1.5

In [2]:
vd = 3.75

In [3]:
type(vu)

float

In [4]:
vu + vd

5.25

In [5]:
import numpy as np

In [6]:
v = np.array((vu, vd))

In [7]:
v

array([1.5 , 3.75])

In [8]:
v.dtype

dtype('float64')

In [9]:
v.shape

(2,)

In [10]:
v + v

array([3. , 7.5])

In [11]:
3 * v

array([ 4.5 , 11.25])

In [12]:
S = np.array((20, 5))

In [13]:
K = 15

In [14]:
C = np.maximum(S - K, 0)

In [15]:
C

array([5, 0])